<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'App\\www\\Controllers\\__class' => $baseDir . '/App/www/Controllers/__class.php',
    'Vobo\\Exception\\Error' => $baseDir . '/Vobo/Exception/Error.php',
    'Vobo\\Internal\\Assets\\Pages' => $baseDir . '/Vobo/Internal/Assets/Pages.php',
    'Vobo\\Internal\\Database\\Pdo' => $baseDir . '/Vobo/Internal/Database/Pdo.php',
    'Vobo\\Internal\\Model\\Model' => $baseDir . '/Vobo/Internal/Model/Model.php',
    'Vobo\\Kernel\\Filter' => $baseDir . '/Vobo/Kernel/Filter.php',
    'Vobo\\Kernel\\Kernel' => $baseDir . '/Vobo/Kernel/Kernel.php',
    'Vobo\\Kernel\\Url' => $baseDir . '/Vobo/Kernel/Url.php',
    'Vobo\\Middleware\\Middleware' => $baseDir . '/Vobo/Middleware/Middleware.php',
    'Vobo\\Mode\\Request' => $baseDir . '/Vobo/Mode/Request.php',
    'Vobo\\Router\\Router' => $baseDir . '/Vobo/Router/Router.php',
    'Vobo\\Settings\\App' => $baseDir . '/Vobo/Settings/App.php',
    'Vobo\\Settings\\Kernel' => $baseDir . '/Vobo/Settings/Kernel.php',
    'Vobo\\Support\\Header' => $baseDir . '/Vobo/Support/Header.php',
    'Vobo\\Support\\Json' => $baseDir . '/Vobo/Support/Json.php',
    'Vobo\\Support\\Support' => $baseDir . '/Vobo/Support/Support.php',
    'Vobo\\Support\\Translate' => $baseDir . '/Vobo/Support/Translate.php',
);
